### ISSUE TITLE
Can't install on Python >3.10

### ISSUE THREAD

**Issue by kitschpatrol** [lkubb/dooti#1]
Hi thanks for this utility, it looks great.

Python 3.10 appears to work, but I'm getting errors when attempting to install under Python 3.11 and 3.12. This is on macOS Sonoma 14.6.1 / arm64.

Here are the logs from attempted installs in each environment:

[3.11](https://gist.github.com/kitschpatrol/902c62b984ccbf4e3ef401e0151c1fc8)

[3.12](https://gist.github.com/kitschpatrol/a2f75b07569a79ad3f563bb482888b3f)

Easy enough to work around with `uv tool install dooti --python 3.10 --with setuptools`, but thought I'd point it out since the package is marked compatible with `^3.10`.

**Comment by lkubb** [comment]
Thanks a lot for taking the time to submit this bug report, much appreciated!

I wanted to rework the packaging anyways, will do so in the near future. :)

**Comment by lkubb** [comment]
This is fixed now in `v0.2.2` 👍 (I removed dependency pinning altogether and added a CI test suite).
